#!/bin/bash
IMAGE=grandrounds/license_finder
NOLOGIN=true

while [ $# -gt 0 ] ; do
  case $1 in
  -x) NOLOGIN=bash ;;
  -? | -h) echo "Usage: ${0} [-x] [-?] some command for the container" ; exit 1;;
  *) break ;;
  esac
  shift
done

if [[ ! -d ~/.ssh/docker_ssh ]] ; then
  cat <<-ERR
    You must set up a ~/.ssh/docker_ssh directory with your ssh private key
    available in it, so bundler (and its ilk) can pull private gems into the
    docker container for analysis.  In Linux, it must be owned by *root*,
    permissioned 0700, and have your private key in a file owned by *root* with
    mode 0600.

    This may not be necessary in MacOS (you may be able to just map your ~/.ssh
    to the container's /root/.ssh); modify $0 accordingly if that proves true.
ERR
  exit 1
fi

if `which docker > /dev/null`; then
  docker run \
    -v $PWD:/scan \
    -v ~/.ssh/docker_ssh:/root/.ssh \
    -v $(dirname $SSH_AUTH_SOCK):$(dirname $SSH_AUTH_SOCK) \
    -e SSH_AUTH_SOCK=$SSH_AUTH_SOCK \
    -it ${IMAGE} /bin/bash \
    -lc "cd /scan && $(echo $@) && ${NOLOGIN}"
else
  echo "You do not have docker installed. Please install it:"
  echo "    https://docs.docker.com/engine/installation/"
  exit 1
fi
